name: buscatelo
description: Hotel finding. An awesome Flutter challenge.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: any
  provider: any
  bordered_text: ^2.0.0
  go_router: ^14.6.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.5
  firebase_core: ^3.9.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  google_sign_in: ^6.2.2
  flutter_stripe: ^11.3.0
  google_maps_flutter: ^2.10.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  pedantic: ^1.8.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/logo.png"
  image_path_android: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/home.jpg
    - assets/img/hotel1.jpg
    - assets/img/hotel2.jpg
    - assets/img/hotel3.jpg
    - assets/img/room1.jpg
    - assets/img/room2.jpg
    - assets/img/room3.jpg
    - assets/img/room4.jpg
    - server/hotels.json
